apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/RitzLearnsK8s/platform-infra.git'
    targetRevision: main
    path: clusters/eks-platform
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
